title: Xusong Li's Homepage
page-top-title: Xusong Li
top-section-bg-text: Material Science and Engineering
home-subtitle: Xusong Li&ensp;|&ensp;李旭嵩
copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'
